[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "CMS_ACCESS_CONTROL_GUIDE.md,CMS_USER_GUIDE.md"

# Redirect rules for clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling
[build.processing]
  skip_processing = false

# Branch deploy settings for PR previews
[context.branch-deploy]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
