backend:
  name: git-gateway
  branch: main

# Local development configuration
local_backend: true

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  # Site Contact Information
  - name: "settings"
    label: "🏢 Contact Information"
    files:
      - label: "Contact Details"
        name: "site"
        file: "src/_data/site.json"
        fields:
          - { label: "School Email", name: "email", widget: "string" }
          - { label: "Phone Number", name: "phone", widget: "string", required: false }
          - { label: "Instagram Handle", name: "instagram", widget: "string", hint: "Don't include @" }
          - { label: "Location/Address", name: "location", widget: "string" }

  # Program Information - Easy to Update
  - name: "programs_data"
    label: "🎸 Programs & Pricing"
    files:
      - label: "Learn To Play Program"
        name: "learn_to_play"
        file: "src/_data/programs/learn_to_play.json"
        fields:
          - { label: "Program Name", name: "name", widget: "string", hint: "Currently: Learn To Play" }
          - { label: "Price", name: "price", widget: "string", hint: "e.g., $150/month" }
          - { label: "Duration", name: "duration", widget: "string", hint: "e.g., 8 weeks" }
          - { label: "Description", name: "description", widget: "text", hint: "Brief program overview" }
          - label: "What Students Learn"
            name: "curriculum"
            widget: "list"
            hint: "Add/remove curriculum items"
            field: { label: "Learning Goal", name: "item", widget: "string" }

      - label: "Bandstarter Program"
        name: "bandstarter"
        file: "src/_data/programs/bandstarter.json"
        fields:
          - { label: "Program Name", name: "name", widget: "string", hint: "Currently: Bandstarter" }
          - { label: "Price", name: "price", widget: "string", hint: "e.g., $200/month" }
          - { label: "Duration", name: "duration", widget: "string", hint: "e.g., 12 weeks" }
          - { label: "Description", name: "description", widget: "text", hint: "Brief program overview" }
          - label: "What Students Learn"
            name: "curriculum"
            widget: "list"
            hint: "Add/remove curriculum items"
            field: { label: "Learning Goal", name: "item", widget: "string" }

      - label: "Show Ready Program"
        name: "show_ready"
        file: "src/_data/programs/show_ready.json"
        fields:
          - { label: "Program Name", name: "name", widget: "string", hint: "Currently: Show Ready" }
          - { label: "Price", name: "price", widget: "string", hint: "e.g., $250/month" }
          - { label: "Duration", name: "duration", widget: "string", hint: "e.g., 16 weeks" }
          - { label: "Description", name: "description", widget: "text", hint: "Brief program overview" }
          - label: "What Students Learn"
            name: "curriculum"
            widget: "list"
            hint: "Add/remove curriculum items"
            field: { label: "Learning Goal", name: "item", widget: "string" }

      - label: "Tour Program"
        name: "tour"
        file: "src/_data/programs/tour.json"
        fields:
          - { label: "Program Name", name: "name", widget: "string", hint: "Currently: Tour" }
          - { label: "Price", name: "price", widget: "string", hint: "e.g., $300/month" }
          - { label: "Duration", name: "duration", widget: "string", hint: "e.g., Ongoing" }
          - { label: "Description", name: "description", widget: "text", hint: "Brief program overview" }
          - label: "What Students Learn"
            name: "curriculum"
            widget: "list"
            hint: "Add/remove curriculum items"
            field: { label: "Learning Goal", name: "item", widget: "string" }

  # Lesson Pricing
  - name: "pricing_data"
    label: "💰 Individual Lessons"
    files:
      - label: "Individual Lesson Pricing"
        name: "individual_lessons"
        file: "src/_data/pricing/individual_lessons.json"
        fields:
          - label: "Lesson Options"
            name: "lessons"
            widget: "list"
            hint: "Add/edit/remove different lesson types"
            fields:
              - { label: "Lesson Type", name: "name", widget: "string", hint: "e.g., Private Guitar Lesson" }
              - { label: "Description", name: "description", widget: "string", hint: "Brief description" }
              - { label: "Price", name: "price", widget: "string", hint: "e.g., $45/hour" }
              - { label: "Duration", name: "duration", widget: "string", required: false, hint: "e.g., 1 hour" }

      - label: "Recording Services"
        name: "recording_pricing"
        file: "src/_data/pricing/recording.json"
        fields:
          - { label: "Hourly Rate", name: "hourly_rate", widget: "string", hint: "e.g., $50/hour" }
          - { label: "Minimum Hours Required", name: "minimum_hours", widget: "number", hint: "Minimum booking" }
          - { label: "Block Package Price", name: "block_price", widget: "string", hint: "e.g., $400 for 10 hours" }
          - { label: "Block Package Hours", name: "block_hours", widget: "number", hint: "Hours in package deal" }
          - label: "Additional Services"
            name: "addons"
            widget: "list"
            hint: "Extra services available"
            fields:
              - { label: "Service", name: "service", widget: "string", hint: "e.g., Mixing & Mastering" }
              - { label: "Price", name: "price", widget: "string", hint: "e.g., $100 per song" }

  # Policy Documents - Individual Markdown files
  - name: "policies"
    label: "📋 School Policies"
    folder: "src/policies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Policy Title", name: "title", widget: "string" }
      - { label: "Short Summary", name: "summary", widget: "text", hint: "Brief description for policy cards" }
      - { label: "Icon", name: "icon", widget: "select", options: ["fas fa-handshake", "fas fa-calendar-times", "fas fa-shield-alt", "fas fa-camera", "fas fa-music", "fas fa-file-text"], default: "fas fa-file-text", hint: "Choose an appropriate icon" }
      - { label: "Card Style", name: "cardStyle", widget: "select", options: ["light", "primary", "secondary", "warning"], default: "light", hint: "Visual style of the policy card" }
      - { label: "Display Order", name: "order", widget: "number", hint: "Lower numbers appear first (1, 2, 3...)" }
      - { label: "Optional Policy", name: "isOptional", widget: "boolean", default: false, hint: "Check if this policy is optional (like media consent)" }
      - { label: "Policy Content", name: "body", widget: "markdown", hint: "Full policy text - you can use simple formatting" }

# Editor settings
editor:
  preview: true
